### ISSUE TITLE
getEpochTimestamp returning NaN

### ISSUE THREAD

**Issue by louisjmorgan** [davidcalhoun/tle.js#28] opened 2022-01-05 16:56 UTC
When I use the getEpochTimestamp function it returns a NaN. All other get functions are working as expected.

`function convertTLE(tle) {
    const satelliteData = {
      name: getSatelliteName(tle),
      semiMajorAxis: getSemiMajorAxis(getMeanMotion(tle)),
      eccentricity: getEccentricity(tle),
      inclination: getInclination(tle),
      rightAscension: getRightAscension(tle),
      perigee: getPerigee(tle),
      meanAnomaly: getMeanAnomaly(tle),
      epoch: getEpochTimestamp(tle),
    };
    console.log(getEpochTimestamp(tle));
    return satelliteData;
  }`

**Comment by davidcalhoun** [comment] 2022-01-05 17:24
Thanks for the heads up - can you provide the tle you're inputting?  The test seems to be working fine using the ISS's tle.

**Comment by louisjmorgan** [comment] 2022-01-05 17:48
Wow thanks for the prompt response!

I'm using the ISS one from celestrak, I suspected this could be the issue but the format looks right to me:

const tle = `ISS (ZARYA)
  1 25544U 98067A   22005.58472471  .00003968  00000+0  77828-4 0  9998
  2 25544  51.6440  61.8159 0005338   6.5542 157.7978 15.49868185319960`;

thanks in advance,
Louis
________________________________

**Comment by davidcalhoun** [comment] 2022-01-05 17:58
On first glance it looks like there's an extra two spaces in front of line 1 and 2?  Could you try with this instead?

```
const tle = `ISS (ZARYA)
1 25544U 98067A   22005.58472471  .00003968  00000+0  77828-4 0  9998
2 25544  51.6440  61.8159 0005338   6.5542 157.7978 15.49868185319960`;
```

**Comment by louisjmorgan** [comment] 2022-01-06 12:38
Unfortunately that's not working either. I've tried copying tle strings directly from your _tests​_ folder and those are not working either. As I said before the other getters are all working as expected.

________________________________

**Comment by davidcalhoun** [comment] 2022-01-06 15:24
Weird, I'm not sure what's happening, I can't reproduce it.  I tried it on both Node.js v14.17.5 and v16.13.1 and it works.  Added this test, which passes on my side:

```js
test("getEpochTimestamp 2", () => {
	const tle = `ISS (ZARYA)
1 25544U 98067A   22005.58472471  .00003968  00000+0  77828-4 0  9998
2 25544  51.6440  61.8159 0005338   6.5542 157.7978 15.49868185319960`;
	expect(getEpochTimestamp(tle)).toEqual(1641391320214);
});
```

**Comment by louisjmorgan** [comment] 2022-01-06 16:56
I'm using Node v16.13.1 with react and webpack, but all the calculations are contained within a single react component so I'm not sure that's affecting anything. The console output for the TLE looked normal:

ISS (ZARYA)
1 25544U 98067A   22005.58472471  .00003968  00000+0  77828-4 0  9998
2 25544  51.6440  61.8159 0005338   6.5542 157.7978 15.49868185319960

I'll try running your test in a basic two file node setup shortly and let you know if it exhibits the same behaviour.

Thanks again for your help,
Louis
________________________________

**Comment by thkruz** [comment] 2022-07-26 02:22
@louisjmorgan did you have any luck? Would be nice to close this issue if it works now.

**Comment by louisjmorgan** [comment] 2022-07-27 11:03
No to be honest I didn't. I switched to using [satellite-js](https://github.com/shashwatak/satellite-js) which was more suited to my needs as I'm calculating orbital positions.

**Comment by davidcalhoun** [comment] 2022-11-11 23:44
Closing this out as I'm unable to reproduce.

**Closed by davidcalhoun** 2022-11-11 23:44 UTC
